### ISSUE TITLE
sctp ERROR: ... stream 3 not found / with Firefox

### ISSUE THREAD

**Issue by chrbsg** [pion/sctp#150]
### Your environment.
  - Version: v2.2.25
  - Browser: Firefox
  - Other Information - 

### What did you do?

Close peerconnection at end of session 

### What did you expect?
No errors

### What happened?

Repeated errors like:

```
sctp ERROR: 2020/09/22 19:46:50 [0xc000116b60] stream 3 not found)
sctp ERROR: 2020/09/22 19:46:50 [0xc000116b60] stream 3 not found)
sctp ERROR: 2020/09/22 19:46:50 [0xc000116b60] stream 3 not found)
sctp ERROR: 2020/09/22 19:46:50 [0xc000116b60] stream 3 not found)
sctp ERROR: 2020/09/22 19:46:50 [0xc000116b60] stream 3 not found)
sctp ERROR: 2020/09/22 19:46:50 [0xc000116b60] stream 3 not found)
sctp ERROR: 2020/09/22 19:46:50 [0xc000116b60] stream 3 not found)
sctp ERROR: 2020/09/22 19:46:50 [0xc000116b60] stream 3 not found)
```

This does not happen with Chrome.

**Comment by Sean-Der** [comment]
Thanks for reporting @chrbsg Are you closing the PeerConnection in Pion or FireFox?

My guess would be that the stream is reaped. But a routine internally is still trying to use it? I am not exactly sure, but this should be easy to enough to reproduce.

**Comment by chrbsg** [comment]
The PeerConnection is closed in Firefox.

**Comment by dosgo** [comment]
![image](https://user-images.githubusercontent.com/9545458/101015064-c66d7100-35a1-11eb-9bb1-2e8e8fc40a63.png)
dtls+sctp

**Comment by enobufs** [comment]
This might be related to #176.

**Comment by enobufs** [comment]
Closing as it is stale. (#176 has been resolved also)
