### ISSUE TITLE
What is the difference with Linux SCTP? 

### ISSUE THREAD

**Issue by sunfeilong** [pion/sctp#200]
I think RFC4960 is an OS layer protocol. But this repository use `net.Conn` to implement it. So I think this repository is not SCTP, Is anything the matter?

**Comment by Sean-Der** [comment]
Hi @sunfeilong 

This SCTP implementation was designed to be transport agnostic. The primary user is [pion/webrtc](https://github.com/pion/webrtc) but there is no reason you can't translate the messages to layer 3 with a `net.Conn` implementation.

**Comment by sunfeilong** [comment]
@Sean-Der Tnahk you for your reply，I am looking for information about the sctp protocol.
