### ISSUE TITLE
SACK chunks followed by other chunks are incorrectly handled.

### ISSUE THREAD

**Issue by ghost** [pion/sctp#204]
Hi,

This is just a curtesy bug report.

You may be aware of `webrtc-rs/sctp`, which is a 1:1 Rust port of `pion/sctp`.

**Well I just submitted a [fix in their codebase](https://github.com/webrtc-rs/sctp/pull/6) that I believe also affects you.**

Basically, the handling of SACK chunks as it is written now incorrectly fails when two chunks are buffered inside the same packet. The fix is trivial: just changing a `==` to a `<`.

**Comment by Sean-Der** [comment]
Thank you so much @jkauffmann-legion! Really appreciate you took the time to file over here as well :)

I will work on porting that fix

**Comment by cnderrauber** [comment]
It is not a bug in this repo, the `chunkHeader.raw` is updated to current chunk length [here](https://github.com/pion/sctp/blob/e23ff7ac4766737136ff9ce375a9759260931adc/chunkheader.go#L79).
