### ISSUE TITLE
Reliability

### ISSUE THREAD

**Issue by backkem** [pion/sctp#21]
In order to pass the libp2p test cases used in [backkem/go-libp2p-webrtc-direct](https://github.com/backkem/go-libp2p-webrtc-direct) we should be able to pass the `TestAssocStressDuplex` test for about 15000000 messages. Right now, I'm able to make it work with around 1500 messages. More will break the current implementation and cause the test to hang forever.
As discussed before this is likely caused by a combination of SACK storm (reader far behind), packet loss and no re-transmission timer to fall back on.

This can probably be fixed by a combination of T3 timer (#11) and a simple congestion window (#14).

**Comment by enobufs** [comment]
Would it be easy to run libp2p tests to very the PR #26 fixes or mitigate the situation?

**Comment by backkem** [comment]
I added go modules support earlier today so that should make this easier. All you'd need to do is un-comment the more advanced tests in `webrtcdirect_test.go`. I did also notice that these tests where overflowing the buffer that was added in pions/ice. That was a bit concerning. I'll look further into this tomorrow.

**Comment by enobufs** [comment]
@backkem can you confirm this has been resolved?

**Comment by backkem** [comment]
Yes, closing.
