### ISSUE TITLE
Problems when transmitting ordered data. Unordered data too.

### ISSUE THREAD

**Issue by hugoArregui** [pion/sctp#63]
This may not be a problem in sctp, maybe there is a bug on the example or I'm missing something but since I have a reproducible case I think it's interesting to document it.

The code is in here: https://github.com/hugoArregui/testsctp/tree/topic-ordered-problem

I see this on the receiver end:

```
2019/09/26 12:43:31 Received Mbps: 19.459, totalBytesReceived: 2551268
sctp DEBUG: 12:43:31.348204 association.go:967: [0xc0000a5380] receive buffer full. dropping DATA with tsn=3502769449
2019/09/26 12:43:32 Received Mbps: 9.736, totalBytesReceived: 2552496
2019/09/26 12:43:33 Received Mbps: 6.491, totalBytesReceived: 2552496
sctp DEBUG: 12:43:33.348266 association.go:967: [0xc0000a5380] receive buffer full. dropping DATA with tsn=3502769449
2019/09/26 12:43:34 Received Mbps: 4.870, totalBytesReceived: 2553724
2019/09/26 12:43:35 Received Mbps: 3.896, totalBytesReceived: 2553724
2019/09/26 12:43:36 Received Mbps: 3.247, totalBytesReceived: 2553724
2019/09/26 12:43:37 Received Mbps: 2.783, totalBytesReceived: 2553724
sctp DEBUG: 12:43:37.348694 association.go:967: [0xc0000a5380] receive buffer full. dropping DATA with tsn=3502769449
2019/09/26 12:43:38 Received Mbps: 2.437, totalBytesReceived: 2554952
2019/09/26 12:43:39 Received Mbps: 2.166, totalBytesReceived: 2554952
```

And this on the sender end:
```
2019/09/26 12:43:31 Sent Mbps: 19.461, totalBytesSent: 2551268, bufferedAmout: 557056
sctp DEBUG: 12:43:31.347734 association.go:2011: [0xc00009f380] T3-rtx timed out: nRtos=1 cwnd=1228 ssthresh=41486
sctp DEBUG: 12:43:31.347962 association.go:518: [0xc00009f380] retransmitting 1228 bytes
2019/09/26 12:43:32 Sent Mbps: 9.736, totalBytesSent: 2552496, bufferedAmout: 557056
2019/09/26 12:43:33 Sent Mbps: 6.491, totalBytesSent: 2552496, bufferedAmout: 557056
sctp DEBUG: 12:43:33.348043 association.go:2011: [0xc00009f380] T3-rtx timed out: nRtos=2 cwnd=1228 ssthresh=4912
sctp DEBUG: 12:43:33.348124 association.go:518: [0xc00009f380] retransmitting 1228 bytes
2019/09/26 12:43:34 Sent Mbps: 4.871, totalBytesSent: 2553724, bufferedAmout: 557056
2019/09/26 12:43:35 Sent Mbps: 3.897, totalBytesSent: 2553724, bufferedAmout: 557056
2019/09/26 12:43:36 Sent Mbps: 3.247, totalBytesSent: 2553724, bufferedAmout: 557056
2019/09/26 12:43:37 Sent Mbps: 2.783, totalBytesSent: 2553724, bufferedAmout: 557056
sctp DEBUG: 12:43:37.348328 association.go:2011: [0xc00009f380] T3-rtx timed out: nRtos=3 cwnd=1228 ssthresh=4912
sctp DEBUG: 12:43:37.348477 association.go:518: [0xc00009f380] retransmitting 1228 bytes
```

I think for some reason the ressembly queue cannot be read (missing some package or there is a bug somewhere) that causes the buffer to be always full which causes the sender to halt.

**Comment by hugoArregui** [comment]
I found something, a chunk is missing in the server side and since a chunk is missing the ssn of the stream is incosistent. AFAICT the chunk is sent from the client but the server never get's it,
the reseembly queue ssn is smallest that any chunk in the queue, so it never process any of his chunks.

I don't know if I'm making sense, this is what happen AFAICT:
- client sends chunk 1,2,3,4,5.. n
- server receives 1,2,3  5..n
- the condition to increase the ressembly queue nextSSN is to receive the next ssn, but the next ssn at some point is 4
- since the nextSSN never get's 4, it's stuck there, so for chunks >= 4 although it gets them, it cannot process them

**Comment by hugoArregui** [comment]
building with `-race` seems to prevent the problem!

**Comment by hugoArregui** [comment]
I saw this on the server side:

```
sctp DEBUG: 19:15:39.232315 association.go:748: [0xc0000a51e0] chunkInit received in state 'Closed'
sctp DEBUG: 19:15:39.232929 association.go:900: [0xc0000a51e0] COOKIE-ECHO received in state 'Closed'
sctp DEBUG: 19:15:39.232965 association.go:713: [0xc0000a51e0] state change: 'Closed' => 'Established'
sctp DEBUG: 19:15:39.234451 association.go:1061: [0xc0000a51e0] accepted a new stream (streamIdentifier: 22)
```

and the code indicates:

```
    if state != cookieWait {
        // RFC 4960
        // 5.2.3.  Unexpected INIT ACK
        //   If an INIT ACK is received by an endpoint in any state other than the
        //   COOKIE-WAIT state, the endpoint should discard the INIT ACK chunk.
        //   An unexpected INIT ACK usually indicates the processing of an old or
        //   duplicated INIT chunk.
        return nil
    }
```

Probably this prevents the client/server to sync on the stream parameters, furthermore I think this is also causing a missalign, I see how at some point the client sends a fwdTsn but the server has fwdTsn disabled

**Comment by hugoArregui** [comment]
I was able to trace back the problem to this:

- at some point the reassembly queue is full, but since the stream is ordered, if the first chunk is missing the queue won't be readable.
- The queue is not readable, so it cannot process new chunks
- The queue doesn't get new chunks because is full so it won't ever be readeable again.

I was able to hack my way around the problem by changing the association handle data in this way:

```
	canPush := a.payloadQueue.canPush(d, a.peerLastTSN)
	if canPush {
		s := a.getOrCreateStream(d.streamIdentifier)
		if s == nil {
			// silentely discard the data. (sender will retry on T3-rtx timeout)
			// see pion/sctp#30
			a.log.Debugf("discard %d", d.streamSequenceNumber)
			return nil
		}

		if a.getMyReceiverWindowCredit() > 0 {
			// Pass the new chunk to stream level as soon as it arrives
			a.payloadQueue.push(d, a.peerLastTSN)
			s.handleData(d)
		} else if !d.unordered &&
			len(s.reassemblyQueue.unordered) == 0 {
			a.log.Debugf("[%s] buffer full, but reassemblyQueue is missing a chunk tsn=%d ssn=%d", a.name, d.tsn,d.streamSequenceNumber)
				a.payloadQueue.push(d, a.peerLastTSN)
				s.handleData(d)
		} else {
			a.log.Debugf("[%s] receive buffer full. dropping DATA with tsn=%d ssn=%d", a.name, d.tsn,d.streamSequenceNumber)
		}
	}
```

There may be an underline problem but I need to read the spec again to remind myself about the dialog between peer when it comes to buffer size and such.

**Comment by enobufs** [comment]
PR #66 fixes a problem with ordered delivery, but my additional vnet test indicated, the buffer full lock-up happens with the unordered stream as well.

Modified fix incoming!

**Comment by hugoArregui** [comment]
How can this happen with unordered delivery if the queue will always be readable if there is some unordered chunk there?

**Comment by enobufs** [comment]
Say, you are sending two messages, A,  and then B. With unordered, it could be received, B then A when unordered is true. (B is readable before A)

When both of the messages are 40KB, for instance, then B won't be fit in the buffer unless A is read by the app. If A has a missing chunk, this would be a dead-lock with the earlier code.
