### ISSUE TITLE
sctp Server start with state closed, which prevent the cookie exchange with the client

### ISSUE THREAD

**Issue by hugoArregui** [pion/sctp#64]
- server association is created with sctp.Server, which set state to close (well, it doesn't set the state really)
- client association is created with sctp.Client, which set the state to cookie-wait

client sends cookie but is ignored by the server because:

```
	if state != cookieWait {
		// RFC 4960
		// 5.2.3.  Unexpected INIT ACK
		//   If an INIT ACK is received by an endpoint in any state other than the
		//   COOKIE-WAIT state, the endpoint should discard the INIT ACK chunk.
		//   An unexpected INIT ACK usually indicates the processing of an old or
		//   duplicated INIT chunk.
		return nil
	}
```

**Comment by enobufs** [comment]
Both clinet and server starts with Closed state. The client, however, sends Init chunk right away, transitions to cookie-wait state.

The server socket never transitions to cookie-wait (== never sends Init chunk). The above code is effectively only for the client.

@hugoArregui If this makes sense to you, can we close this issue?

**Comment by hugoArregui** [comment]
Yes, I think I saw the exchange not happening between a server and a client, but if this is not the cause then the issue is wrong, I'll try to see if I can reproduce it again and create a new one. Thanks!
